# Generated by Django 5.2.1 on 2025-05-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
