# Generated by Django 5.2.1 on 2025-05-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=500)),
                ('categoria', models.CharField(choices=[('Facturación', 'Facturación'), ('Daños', 'Daños'), ('Servicio interrumpido', 'Servicio interrumpido'), ('Atención al cliente', 'Atencion al cliente'), ('Otro', 'Otro')], max_length=30)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('ticket', models.CharField(max_length=10, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
