# Generated by Django 5.2.1 on 2025-05-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reclamos', '0002_reclamo_estado_alter_reclamo_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
